configName: dsi_xlcdc_9x75cur_wsRnd
folderName: thermo_9x75_cur_ws4in_r
format_version: v1.0
frameworkPath: C:\Users\c40450\harmony3
processor: SAM9X75D2G
projectName: thermo_9x75_cur_ws4in_r
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X7_DFP\1.1.120
