#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# dsi_xlcdc_9x75curiosity_wsRnd configuration
CND_ARTIFACT_DIR_dsi_xlcdc_9x75curiosity_wsRnd=dist/dsi_xlcdc_9x75curiosity_wsRnd/production
CND_ARTIFACT_NAME_dsi_xlcdc_9x75curiosity_wsRnd=thermo_9x75_curiosity_ws4in_r.X.production.hex
CND_ARTIFACT_PATH_dsi_xlcdc_9x75curiosity_wsRnd=dist/dsi_xlcdc_9x75curiosity_wsRnd/production/thermo_9x75_curiosity_ws4in_r.X.production.hex
